###################
# 1, To see more configuration properties goto: https://spring.io/projects/spring-boot#learn
#
# 2, How to read yaml data in the program?
#     Use: @Value("${propertyName1[0].propertyName2[0]}") before defining a variable
#
# 3, How to reference data in yaml?
#     newProperty: S{oldProperty} add info
#
# 4, To use escape characters, you need to enclose the content in "".
#
# 5, To read all yaml data in one variable, Use the variable:   @Autowired   private Environment env;
#
# 6, How to encapsulate data with a Class?
#    1) create a class
#    2) define variables which have the same names with the properties needed to be encapsulated
#    3) add @Component before the Class
#    4) add @ConfigurationProperties("propertyName")



#fundmentals
server:
  port: 80

spring:
  main:
    banner-mode: console
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/springboot_demo_db
    username: root
    password: mysqlrootpassword
    type: com.alibaba.druid.pool.DruidDataSource


#Mybatis Plus Configurations
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_ #数据表前缀
      id-type: auto #数据自增策略
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启MP日志，上线运行时不要开

#Coustom
# country: China
# city: "Shi Jiazhuang"
# name: "Cai Xukun"
# hobby:
#   - sing
#   - dance

#   - rap